"""
Comprehensive test suite for example.com generated by AI-powered testing pipeline.

This test suite demonstrates the complete AI-powered testing workflow:
1. Systematic website exploration using MCP servers
2. AI-generated test cases based on accessibility analysis
3. Comprehensive coverage following best practices
4. Integration with Allure reporting and CI/CD pipeline
"""

import pytest
from playwright.sync_api import Page, expect
from typing import Any, Optional
import re
import allure


@allure.epic("Example Domain Testing")
@allure.feature("Website Structure and Functionality")
class TestExampleDomainComprehensive:
    """
    Comprehensive test suite for example.com following playwright-tester mode guidelines.

    Generated by AI-powered testing pipeline using:
    - Context7 MCP for documentation and best practices
    - Playwright MCP for systematic website exploration
    - Sequential Thinking MCP for test strategy planning
    - Fetch MCP for web data processing
    """

    @pytest.fixture(autouse=True)
    def setup_test(self, page: Page) -> None:
        """
        Setup for each test method using accessibility-first approach.

        This fixture follows the project's base URL configuration pattern
        and ensures consistent test environment setup.
        """
        self.page = page
        self.base_url = "https://example.com"
        self.page.goto(self.base_url)

        # Set viewport for consistent testing
        self.page.set_viewport_size({"width": 1280, "height": 720})

    @allure.title("Website Loading and Basic Structure")
    @allure.description(
        "Test basic website loading and structure using accessibility-first locators"
    )
    @allure.severity(allure.severity_level.CRITICAL)
    @allure.story("Basic Functionality")
    def test_website_loading_and_basic_structure(self) -> None:
        """
        Test basic website loading and structure using accessibility-first locators.

        This test verifies:
        - Page loads successfully
        - Title is correct
        - Main heading is visible
        - Page structure is accessible
        """
        # Basic page loading checks using web-first assertions
        expect(self.page).to_have_title("Example Domain")
        expect(self.page.locator("body")).to_be_visible()

        # Check for main heading using accessibility-first approach
        main_heading = self.page.get_by_role("heading", name="Example Domain")
        expect(main_heading).to_be_visible()
        # Verify heading content
        expect(main_heading).to_contain_text("Example Domain")

        # Verify page has essential content structure
        content_paragraph = self.page.get_by_text(
            "documentation examples without needing permission"
        )
        expect(content_paragraph).to_be_visible()

        # Take screenshot for visual verification
        self.page.screenshot(path="example-domain-structure.png")

    @allure.title("Accessibility and Semantic Structure")
    @allure.description("Test accessibility requirements and semantic HTML structure")
    @allure.severity(allure.severity_level.NORMAL)
    @allure.story("Accessibility")
    def test_accessibility_and_semantic_structure(self) -> None:
        """
        Test accessibility requirements and semantic HTML structure.

        This test verifies:
        - Proper heading hierarchy
        - Semantic HTML structure
        - Accessibility attributes
        - Screen reader compatibility
        """
        # Check for proper heading structure
        headings = self.page.locator("h1, h2, h3, h4, h5, h6")
        expect(headings).to_have_count(1)  # Should have exactly one heading

        # Verify main heading is h1
        main_heading = self.page.locator("h1")
        expect(main_heading).to_be_visible()
        expect(main_heading).to_contain_text("Example Domain")

        # Check for proper paragraph structure
        paragraphs = self.page.locator("p")
        expect(paragraphs).to_have_count(2)

        # Verify link accessibility
        info_link = self.page.get_by_role("link", name="Learn more")
        expect(info_link).to_be_visible()
        expect(info_link).to_have_attribute("href", "https://iana.org/domains/example")

    @allure.title("Navigation and Link Functionality")
    @allure.description("Test navigation elements and link functionality")
    @allure.severity(allure.severity_level.NORMAL)
    @allure.story("Navigation")
    def test_navigation_and_link_functionality(self) -> None:
        """
        Test navigation elements and link functionality.

        This test verifies:
        - Links are clickable and functional
        - External links open correctly
        - Link text is descriptive
        - Navigation flow works as expected
        """
        # Test the information link
        info_link = self.page.get_by_role("link", name="Learn more")
        expect(info_link).to_be_visible()
        expect(info_link).to_be_enabled()

        # Verify link destination
        expect(info_link).to_have_attribute("href", "https://iana.org/domains/example")

        # Test link interaction (hover to verify it's interactive)
        info_link.hover()
        expect(info_link).to_be_visible()

        # Take screenshot of link interaction
        self.page.screenshot(path="example-domain-links.png")

    @allure.title("Content Verification and Text Analysis")
    @allure.description("Test content accuracy and text analysis")
    @allure.severity(allure.severity_level.NORMAL)
    @allure.story("Content")
    def test_content_verification_and_text_analysis(self) -> None:
        """
        Test content accuracy and text analysis.

        This test verifies:
        - Content text is correct
        - All expected text elements are present
        - Content structure is logical
        - Text is readable and accessible
        """
        # Verify main content text
        main_content = self.page.get_by_text("documentation examples without needing permission")
        expect(main_content).to_be_visible()

        # Verify link text
        link_text = self.page.get_by_text("Learn more")
        expect(link_text).to_be_visible()

        # Test text content structure
        body_text = self.page.locator("body").text_content()
        assert "Example Domain" in body_text
        assert "documentation examples" in body_text
        assert "Learn more" in body_text

    @allure.title("Responsive Design and Viewport Testing")
    @allure.description("Test responsive design at different viewport sizes")
    @allure.severity(allure.severity_level.NORMAL)
    @allure.story("Responsive Design")
    def test_responsive_design_and_viewport_testing(self) -> None:
        """
        Test responsive design at different viewport sizes.

        This test verifies:
        - Mobile viewport compatibility
        - Tablet viewport compatibility
        - Desktop viewport compatibility
        - Content remains accessible at all sizes
        """
        # Test mobile viewport
        self.page.set_viewport_size({"width": 375, "height": 667})
        expect(self.page.locator("body")).to_be_visible()
        expect(self.page.get_by_role("heading", name="Example Domain")).to_be_visible()

        # Test tablet viewport
        self.page.set_viewport_size({"width": 768, "height": 1024})
        expect(self.page.locator("body")).to_be_visible()
        expect(self.page.get_by_role("heading", name="Example Domain")).to_be_visible()

        # Test desktop viewport
        self.page.set_viewport_size({"width": 1280, "height": 720})
        expect(self.page.locator("body")).to_be_visible()
        expect(self.page.get_by_role("heading", name="Example Domain")).to_be_visible()

        # Take screenshot of responsive layout
        self.page.screenshot(path="example-domain-responsive.png")

    @allure.title("Performance and Loading Metrics")
    @allure.description("Test page performance and loading metrics")
    @allure.severity(allure.severity_level.MINOR)
    @allure.story("Performance")
    def test_performance_and_loading_metrics(self) -> None:
        """
        Test page performance and loading metrics.

        This test verifies:
        - Page loads within acceptable time
        - No critical performance issues
        - Resource loading is efficient
        - User experience is smooth
        """
        # Measure page load time
        start_time = self.page.evaluate("Date.now()")

        # Reload page to measure load time
        self.page.reload()

        # Wait for page to be fully loaded
        self.page.wait_for_load_state("networkidle")

        end_time = self.page.evaluate("Date.now()")
        load_time = end_time - start_time

        # Verify page loads within reasonable time (5 seconds)
        assert load_time < 5000, f"Page load time {load_time}ms exceeds 5 second threshold"

        # Verify page is fully interactive
        expect(self.page.get_by_role("heading", name="Example Domain")).to_be_visible()

        # Take performance screenshot
        self.page.screenshot(path="example-domain-performance.png")

    @allure.title("Error Handling and Edge Cases")
    @allure.description("Test error handling and edge case scenarios")
    @allure.severity(allure.severity_level.NORMAL)
    @allure.story("Error Handling")
    def test_error_handling_and_edge_cases(self) -> None:
        """
        Test error handling and edge case scenarios.

        This test verifies:
        - Page handles missing elements gracefully
        - Error states are handled properly
        - Edge cases don't break functionality
        - Robust error handling
        """
        # Test page navigation to non-existent path
        self.page.goto("https://example.com/nonexistent")

        # Verify page still loads (should redirect or show 404)
        expect(self.page.locator("body")).to_be_visible()

        # Navigate back to main page
        self.page.goto("https://example.com")

        # Verify main content is still accessible
        expect(self.page.get_by_role("heading", name="Example Domain")).to_be_visible()

        # Test JavaScript execution
        result = self.page.evaluate("document.title")
        assert result == "Example Domain"

        # Take screenshot of error handling
        self.page.screenshot(path="example-domain-error-handling.png")


@allure.epic("Example Domain Testing")
@allure.feature("AI-Generated Test Scenarios")
class TestExampleDomainAIGenerated:
    """
    AI-generated test scenarios based on systematic website exploration.

    These tests are generated using the MCP-powered testing pipeline:
    - Systematic exploration using Playwright MCP
    - AI analysis using Sequential Thinking MCP
    - Best practices from Context7 MCP
    - Web data processing using Fetch MCP
    """

    @pytest.fixture(autouse=True)
    def setup_ai_tests(self, page: Page) -> None:
        """Setup for AI-generated test scenarios."""
        self.page = page
        self.page.goto("https://example.com")
        self.page.set_viewport_size({"width": 1280, "height": 720})

    @allure.title("AI-Generated User Journey Testing")
    @allure.description("Test complete user journey as identified by AI analysis")
    @allure.severity(allure.severity_level.NORMAL)
    @allure.story("User Journey")
    def test_ai_generated_user_journey(self) -> None:
        """
        Test complete user journey as identified by AI analysis.

        Based on systematic exploration, the main user journey is:
        1. User lands on example.com
        2. User reads the domain description
        3. User clicks on "Learn more" link
        4. User is redirected to IANA documentation
        """
        # Step 1: Verify initial landing
        expect(self.page).to_have_title("Example Domain")
        expect(self.page.get_by_role("heading", name="Example Domain")).to_be_visible()

        # Step 2: Verify content reading
        description = self.page.get_by_text("documentation examples without needing permission")
        expect(description).to_be_visible()

        # Step 3: Verify link interaction
        info_link = self.page.get_by_role("link", name="Learn more")
        expect(info_link).to_be_visible()
        expect(info_link).to_be_enabled()

        # Step 4: Test link navigation
        with self.page.expect_navigation():
            info_link.click()

        # Verify navigation to IANA (actual redirect URL)
        expect(self.page).to_have_url(re.compile("iana.org"))

        # Take screenshot of user journey
        self.page.screenshot(path="example-domain-user-journey.png")

    @allure.title("AI-Generated Accessibility Analysis")
    @allure.description("Comprehensive accessibility analysis generated by AI")
    @allure.severity(allure.severity_level.NORMAL)
    @allure.story("Accessibility Analysis")
    def test_ai_generated_accessibility_analysis(self) -> None:
        """
        Comprehensive accessibility analysis generated by AI.

        AI analysis identified these accessibility requirements:
        - Proper heading hierarchy
        - Semantic HTML structure
        - Link accessibility
        - Screen reader compatibility
        """
        # Test heading hierarchy
        h1_elements = self.page.locator("h1")
        expect(h1_elements).to_have_count(1)

        # Test semantic structure
        main_content = self.page.locator("body")
        expect(main_content).to_be_visible()

        # Test link accessibility
        links = self.page.get_by_role("link")
        expect(links).to_have_count(1)

        # Test keyboard navigation
        self.page.keyboard.press("Tab")
        focused_element = self.page.locator(":focus")
        expect(focused_element).to_be_visible()

        # Take accessibility screenshot
        self.page.screenshot(path="example-domain-accessibility.png")

    @allure.title("AI-Generated Performance Analysis")
    @allure.description("Performance analysis and optimization recommendations")
    @allure.severity(allure.severity_level.NORMAL)
    @allure.story("Performance Analysis")
    def test_ai_generated_performance_analysis(self) -> None:
        """
        Performance analysis and optimization recommendations.

        AI analysis identified these performance considerations:
        - Page load time optimization
        - Resource efficiency
        - User experience metrics
        - Performance monitoring
        """
        # Measure initial load time
        start_time = self.page.evaluate("performance.now()")

        # Reload to measure performance
        self.page.reload()
        self.page.wait_for_load_state("networkidle")

        end_time = self.page.evaluate("performance.now()")
        load_time = end_time - start_time

        # Verify performance metrics
        assert load_time < 1000, f"Load time {load_time}ms exceeds 1 second threshold"

        # Test resource efficiency (some pages may not have external resources)
        resources = self.page.evaluate("performance.getEntriesByType('resource')")
        # For simple pages like example.com, we may not have external resources
        # Just verify the performance API is available
        assert isinstance(resources, list), "Performance API should return a list"

        # Take performance screenshot
        self.page.screenshot(path="example-domain-performance-analysis.png")
